### ISSUE TITLE
[Feature Request] Disable\hide with a settings module the bot commands of `downtime` , `game` and `campaign`.

### ISSUE THREAD

**Issue by p4535992** [oronder/Oronder#21]
Disable\hide with a settings module the bot commands of `downtime` , `game` and `campaign`.

Not knowing the structure of the bot I don't know if this is possible, but we don't need the commands of `downtime` , `game` and `campaign` even at the level of dungeon masters.

In this case the less commands they see , the less they get confused...is it possible to hide the bot commands by setting a module setting on foundryvtt ?

**Comment by ChunkLightTuna** [comment]
You should be able to do this from your [Discord server settings](https://discord.com/blog/slash-commands-permissions-discord-apps-bots).

![image](https://github.com/user-attachments/assets/9de625ed-82ee-4fba-a4f4-37404d783532)
